import re
from typing import Dict, Any

from app.utils.log_setup import get_logger

logger = get_logger(__name__)


async def render_diagram(
    source: str,
    format: str = "mermaid",
    description: str = "",
) -> Dict[str, Any]:
    """
    Render a diagram from a high-level textual description generated by an LLM.

    The function accepts a natural-language description of the desired diagram and
    produces source code in either GraphViz (DOT) or Mermaid syntax.  It performs
    basic validation of the input, enforces size limits to mitigate abuse, logs the
    process, and returns the rendered diagram together with useful metadata.

    Args:
        source: A non-empty string containing a high-level description of the diagram
            to generate.  The description must be at least ten characters long.
        format: The target diagram language.  Must be either `"graphviz"` or
            `"mermaid"`; defaults to `"mermaid"`.
        description: An optional short text shown in the UI to identify the diagram.
            If omitted, a generic description based on the chosen format is used.

    Returns:
        dict: A mapping with the following keys:

            * `format` - The diagram format that was generated (`"graphviz"`
              or `"mermaid"`).
            * `source` - The generated diagram source code.  If the source exceeds
              5 KB it is truncated and a notice is appended.
            * `size_bytes` - Length of the returned `source` string in bytes.
            * `description` - The UI description supplied by the caller or a default
              one derived from the format.

        In case of validation failures or unexpected errors, the dictionary contains
        an `error` key with a human-readable error message instead of the keys
        listed above.

    Raises:
        None.  All errors are captured and reported in the returned dictionary.
    """
    if format not in ["graphviz", "mermaid"]:
        return {"error": f"Invalid format '{format}'. Must be 'graphviz' or 'mermaid'."}

    if not source or len(source.strip()) < 10:
        return {"error": "Source description must be at least 10 characters."}

    # Limit source size to prevent abuse
    if len(source) > 5000:
        return {"error": "Source description too long (max 5000 characters)."}

    logger.info(f"Rendering {format} diagram: {source[:100]}...")

    try:
        if format == "graphviz":
            diagram_source = _generate_graphviz(source)
        else:  # mermaid
            diagram_source = _generate_mermaid(source)

        # Validate size
        if len(diagram_source) > 5000:
            logger.warning(f"Diagram source exceeds 5KB, truncating...")
            diagram_source = diagram_source[:5000] + "\n... (truncated)"

        logger.info(f"Generated {format} diagram ({len(diagram_source)} chars)")

        return {
            "format": format,
            "source": diagram_source,
            "size_bytes": len(diagram_source),
            "description": description or f"{format.capitalize()} diagram",
        }

    except Exception as e:
        logger.error(f"Diagram generation failed: {e}", exc_info=True)
        return {"error": f"Diagram generation failed: {str(e)[:200]}"}


def _generate_graphviz(description: str) -> str:
    """
    Generate GraphViz DOT source code from a textual description.

    The function parses a multi-line string looking for simple relationship patterns such as
    ```
    A -> B
    A→B
    parent to child
    from X to Y
    ```
    and builds a directed graph in DOT language.

    **Args:**
        description (str): A free-form text describing nodes and edges. Each line may contain one or more
            relationship expressions; the function extracts identifiers composed of word characters
            (`\w+`) as node names.

    **Returns:**
        str: The complete DOT source for a directed graph named `G`. If no relationships are found,
            the output contains a single node labeled with up to the first 100 characters of the
            description (quotes escaped).

    **Raises:**
        None. Errors in parsing are silently ignored; unmatched lines simply do not contribute nodes or edges.
    """
    # Parse description for common patterns
    lines = description.strip().split("\n")

    # Build DOT graph
    dot_lines = ["digraph G {", "  rankdir=LR;", "  node [shape=box, style=rounded];", ""]

    # Extract relationships (simple parser)
    # Looks for patterns like "A -> B", "A→B", "parent→child"
    nodes = set()
    edges = []

    for line in lines:
        # Match arrow patterns
        arrow_patterns = [
            r"(\w+)\s*->\s*(\w+)",
            r"(\w+)\s*→\s*(\w+)",
            r"(\w+)\s+to\s+(\w+)",
            r"from\s+(\w+)\s+to\s+(\w+)",
        ]

        for pattern in arrow_patterns:
            matches = re.findall(pattern, line, re.IGNORECASE)
            for match in matches:
                source, target = match
                nodes.add(source)
                nodes.add(target)
                edges.append((source, target))

    # If no relationships found, create a simple node
    if not nodes:
        dot_lines.append('  "Description" [label="' + description[:100].replace('"', '\\"') + '"];')
    else:
        # Add nodes
        for node in sorted(nodes):
            dot_lines.append(f'  "{node}";')

        dot_lines.append("")

        # Add edges
        for source, target in edges:
            dot_lines.append(f'  "{source}" -> "{target}";')

    dot_lines.append("}")

    return "\n".join(dot_lines)


def _generate_mermaid(description: str) -> str:
    """
    Generate Mermaid diagram source code from a textual description.

    This function examines the provided *description* to determine which type of
    Mermaid diagram is appropriate and then delegates to a specialized generator.
    It supports three primary diagram categories:

    - **Sequence diagrams** - detected when the description contains keywords such as
      `sequence`, `interaction`, `message` or `call`.
    - **Timelines** - detected when the description includes words like `timeline`,
      `chronology` or `time`.
    - **Flowcharts** - used as a fallback for all other descriptions.

    Parameters
    ----------
    description: str
        A natural-language description of the diagram to be created. The text is
        inspected case-insensitively to infer the diagram type.

    Returns
    -------
    str
        The complete Mermaid source code representing the inferred diagram.
        The returned string can be rendered directly by a Mermaid renderer.

    Raises
    ------
    ValueError
        If *description* is empty or only whitespace.
    """
    description_lower = description.lower()

    # Detect diagram type from description
    if any(
        keyword in description_lower for keyword in ["sequence", "interaction", "message", "call"]
    ):
        return _generate_mermaid_sequence(description)
    elif any(keyword in description_lower for keyword in ["timeline", "chronology", "time"]):
        return _generate_mermaid_timeline(description)
    else:
        return _generate_mermaid_flowchart(description)


def _generate_mermaid_flowchart(description: str) -> str:
    """
    Generate a Mermaid flowchart definition from a plain-text description.

    Parameters
    ----------
    description : str
        A multi-line textual description containing node identifiers and relationship
        specifications. Supported relationship syntaxes include `A -> B`, `A → B`,
        `A to B` and `from A to B` (case-insensitive). The function extracts the
        first word of each identifier as a node name.

    Returns
    -------
    str
        A string containing a Mermaid flowchart definition. The output always starts
        with `flowchart LR` followed by either a single labelled node (when no
        relationships are detected) or a series of edge statements in the form
        `source --> target`.

    Notes
    -----
    * Node definitions are implicit; only edges are emitted unless the description
      lacks any recognizable relationship, in which case a fallback node `A`
      with a truncated label of the original description is created.
    * Only alphanumeric word characters (matched by `\w+`) are considered valid
      identifiers. Any surrounding whitespace or punctuation is ignored.
    """
    lines = description.strip().split("\n")

    mermaid_lines = ["flowchart LR"]

    nodes = set()
    edges = []

    # Parse relationships
    arrow_patterns = [
        r"(\w+)\s*->\s*(\w+)",
        r"(\w+)\s*→\s*(\w+)",
        r"(\w+)\s+to\s+(\w+)",
        r"from\s+(\w+)\s+to\s+(\w+)",
    ]

    for line in lines:
        for pattern in arrow_patterns:
            matches = re.findall(pattern, line, re.IGNORECASE)
            for match in matches:
                source, target = match
                nodes.add(source)
                nodes.add(target)
                edges.append((source, target))

    # If no relationships, create simple node
    if not nodes:
        mermaid_lines.append(f'  A["{description[:100]}"]')
    else:
        # Add edges (nodes are implicit in Mermaid)
        for source, target in edges:
            mermaid_lines.append(f"  {source} --> {target}")

    return "\n".join(mermaid_lines)


def _generate_mermaid_sequence(description: str) -> str:
    """
    Generate a Mermaid sequence diagram from a plain-text description.

    Args:
        description (str): A multiline string describing interactions between participants. Each line may contain phrases such as “A calls B”, “A sends B”, “A requests B”, or arrow notations like “A -> B” / “A → B”. The function extracts participant names and messages from these patterns.

    Returns:
        str: The Mermaid source code for a sequence diagram. The output starts with the `sequenceDiagram` keyword, followed by lines defining interactions (`source->>+target: ...`) or simple notes when no participants are detected. Each interaction line is indented two spaces as required by Mermaid syntax.

    Notes:
        * Participant names are identified using word characters (`\w+`). Non-matching lines are ignored.
        * For call patterns, the original line (truncated to 50 characters) is used as the message label.
        * For arrow patterns, a generic label “message” is applied.
        * If no interactions are found, a single note over participant `A` containing up to the first 100 characters of the description is added.
    """
    lines = description.strip().split("\n")

    mermaid_lines = ["sequenceDiagram"]

    # Parse interactions
    # Look for patterns like "A calls B", "A -> B", "B responds to A"
    participants = set()

    for line in lines:
        # Match call patterns
        call_match = re.search(r"(\w+)\s+(?:calls|sends|requests)\s+(\w+)", line, re.IGNORECASE)
        if call_match:
            source, target = call_match.groups()
            participants.add(source)
            participants.add(target)
            mermaid_lines.append(f"  {source}->>+{target}: {line[:50]}")
            continue

        # Match arrow patterns
        arrow_match = re.search(r"(\w+)\s*(?:->|→)\s*(\w+)", line)
        if arrow_match:
            source, target = arrow_match.groups()
            participants.add(source)
            participants.add(target)
            mermaid_lines.append(f"  {source}->>{target}: message")

    # If no interactions found, create simple note
    if not participants:
        mermaid_lines.append(f"  Note over A: {description[:100]}")

    return "\n".join(mermaid_lines)


def _generate_mermaid_timeline(description: str) -> str:
    """
    Generate a Mermaid timeline diagram from a textual description.

    Parameters
    ----------
    description : str
        Multiline text where the first line is used as the diagram title (truncated to 100 characters). Subsequent lines are parsed for date patterns (`YYYY-MM-DD` or `HH:MM`) and associated events; lines without dates become generic events. Empty input results in a placeholder event.

    Returns
    -------
    str
        A string containing Mermaid markup that defines a timeline, ready for rendering by Mermaid tools.
    """
    lines = description.strip().split("\n")

    mermaid_lines = ["timeline"]
    mermaid_lines.append(f'  title {lines[0][:100] if lines else "Timeline"}')

    # Parse timeline entries
    # Look for dates/times and events
    for line in lines[1:]:
        # Match date patterns
        date_match = re.search(r"(\d{4}-\d{2}-\d{2}|\d{2}:\d{2})", line)
        if date_match:
            date = date_match.group(1)
            event = line.replace(date, "").strip()
            mermaid_lines.append(f"  {date} : {event[:100]}")
        elif line.strip():
            mermaid_lines.append(f"  Event : {line.strip()[:100]}")

    # If no entries, add placeholder
    if len(mermaid_lines) <= 2:
        mermaid_lines.append("  Event : See description above")

    return "\n".join(mermaid_lines)


__all__ = ["render_diagram"]
