import re
from typing import List


def sanitize_llm_content(content: str) -> str:
    """
    Remove internal LLM control tokens and deduplicate lines while preserving original order.

    Args:
        content (str): The raw text generated by a language model, potentially containing special control tokens such as `<|...|>` and repeated or looping phrases.

    Returns:
        str: A cleaned version of the input where all control token patterns have been stripped and duplicate non-empty lines (case-insensitive) have been removed, while preserving empty lines and the original line order.
    """
    # Remove <|channel|>, <|constrain|>, <|message|> and similar control tokens
    content = re.sub(r"<\|[^|]+\|>", "", content)

    # Remove repeated phrases (agent getting stuck in loops)
    lines = content.split("\n")
    seen = set()
    unique_lines = []
    for line in lines:
        normalized = line.strip().lower()
        if normalized and normalized not in seen:
            unique_lines.append(line)
            seen.add(normalized)
        elif not normalized:  # Keep empty lines
            unique_lines.append(line)

    return "\n".join(unique_lines)


def remove_duplicate_lines(lines: List[str]) -> List[str]:
    """
    Remove duplicate lines from a sequence while preserving the original order.

    Args:
        lines: A list of strings representing the lines to be processed.

    Returns:
        A new list containing the first occurrence of each non-empty line (case-insensitive, stripped of surrounding whitespace) in its original position. Empty lines are retained unchanged.
    """
    seen = set()
    unique_lines = []
    for line in lines:
        normalized = line.strip().lower()
        if normalized and normalized not in seen:
            unique_lines.append(line)
            seen.add(normalized)
        elif not normalized:  # Keep empty lines
            unique_lines.append(line)
    return unique_lines
